the-gossip-project-rails-master 2/config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :like, only: [:show, :create, :destroy]
  resources :city
  resources :gossips
  resources :user
  resources :comment, except: [:index, :show]
  get 'welcomes/:name', to: 'welcomes#home', as: 'welcome'
  get 'contact/contact'
  get 'team/team'

  root 'gossips#index'
end

the-gossip-project-rails-master 2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

the-gossip-project-rails-master 2/app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true
  validates :zip_code, presence: true

  has_many :users
  has_many :gossips, through: :users 
end

the-gossip-project-rails-master 2/app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :gossip
  belongs_to :user
  has_many :sub_comments
end

the-gossip-project-rails-master 2/app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links
  has_many :comments
  has_many :sub_comments, through: :comment
  has_many :likes
end

the-gossip-project-rails-master 2/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

the-gossip-project-rails-master 2/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  validates :content, presence: true

  belongs_to :sender, class_name: "User"
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: "User", through: :recipient_to_pm_links
end

the-gossip-project-rails-master 2/app/models/sub_comment.rb
class SubComment < ApplicationRecord
  validates :content, presence: true

  belongs_to :comment
  belongs_to :user
end

the-gossip-project-rails-master 2/app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true
  
  has_many :tag_gossip_links
  has_many :gossips, through: :tag_gossip_links
end

the-gossip-project-rails-master 2/app/models/tag_gossip_link.rb
class TagGossipLink < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

the-gossip-project-rails-master 2/app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true, length: { in: 6..200 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :age, presence: true, numericality: { only_integer: true }
  validates :password, presence: true, length: { minimum: 6 }

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
  has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links
  has_many :sub_comments
  has_many :comments
  has_many :likes

  has_secure_password
end

the-gossip-project-rails-master 2/app/helpers/application_helper.rb
module ApplicationHelper
end

the-gossip-project-rails-master 2/app/helpers/city_helper.rb
module CityHelper
end

the-gossip-project-rails-master 2/app/helpers/comment_helper.rb
module CommentHelper
end

the-gossip-project-rails-master 2/app/helpers/contact_helper.rb
module ContactHelper
end

the-gossip-project-rails-master 2/app/helpers/gossips_helper.rb
module GossipsHelper
end

the-gossip-project-rails-master 2/app/helpers/like_helper.rb
module LikeHelper
end

the-gossip-project-rails-master 2/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
   User.find_by(id: session[:user_id])
  end

  def log_in(user)
   session[:user_id] = user.id
  end
end

the-gossip-project-rails-master 2/app/helpers/team_helper.rb
module TeamHelper
end

the-gossip-project-rails-master 2/app/helpers/user_helper.rb
module UserHelper
end

the-gossip-project-rails-master 2/app/helpers/welcomes_helper.rb
module WelcomesHelper
end

the-gossip-project-rails-master 2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to "Home", gossips_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "Contact", contact_contact_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Team", team_team_path, class: 'nav-link' %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to "Déconnexion", session_path(session[:user_id]), method: :delete, class: 'nav-link' %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_path, class: 'nav-link' %></li>
              <li><%= link_to "Sign in", new_session_path, class: 'nav-link' %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>