the-gossip-project-rails-master 2/config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :like, only: [:show, :create, :destroy]
  resources :city
  resources :gossips
  resources :user
  resources :comment, except: [:index, :show]
  get 'welcomes/:name', to: 'welcomes#home', as: 'welcome'
  get 'contact/contact'
  get 'team/team'

  root 'gossips#index'
end

the-gossip-project-rails-master 2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

the-gossip-project-rails-master 2/app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true
  validates :zip_code, presence: true

  has_many :users
  has_many :gossips, through: :users 
end

the-gossip-project-rails-master 2/app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :gossip
  belongs_to :user
  has_many :sub_comments
end

the-gossip-project-rails-master 2/app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links
  has_many :comments
  has_many :sub_comments, through: :comment
  has_many :likes
end

the-gossip-project-rails-master 2/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

the-gossip-project-rails-master 2/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  validates :content, presence: true

  belongs_to :sender, class_name: "User"
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: "User", through: :recipient_to_pm_links
end

the-gossip-project-rails-master 2/app/models/sub_comment.rb
class SubComment < ApplicationRecord
  validates :content, presence: true

  belongs_to :comment
  belongs_to :user
end

the-gossip-project-rails-master 2/app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true
  
  has_many :tag_gossip_links
  has_many :gossips, through: :tag_gossip_links
end

the-gossip-project-rails-master 2/app/models/tag_gossip_link.rb
class TagGossipLink < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

the-gossip-project-rails-master 2/app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true, length: { in: 6..200 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :age, presence: true, numericality: { only_integer: true }
  validates :password, presence: true, length: { minimum: 6 }

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
  has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links
  has_many :sub_comments
  has_many :comments
  has_many :likes

  has_secure_password
end

the-gossip-project-rails-master 2/app/controllers/city_controller.rb
class CityController < ApplicationController

  def show
    @city = City.find(params[:id])
    @gossips_city = City.find(params[:id]).gossips
  end
end

the-gossip-project-rails-master 2/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:create, :show, :new]
  before_action :authenticate_user_edit, only: [:edit, :update]

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: current_user.id) # avec xxx qui sont les données obtenues à partir du formulaire

    if @gossip.save # essaie de sauvegarder en base @gossip
      # si ça marche, il redirige vers la page d'index du site
      puts "Tu as réussi"
      redirect_to gossips_path
    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      puts "ca ne fontionne pas"
      render new_gossip_path
    end
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_user = @gossip.user

    if @gossip.update(gossip_params)
      redirect_to gossip_path
    else
      render edit_gossip_path
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    gossip_user = @gossip.user

    if current_user == gossip_user
      @gossip.destroy
      redirect_to gossips_path
    else
      puts "pas possible"
    end
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end
end

the-gossip-project-rails-master 2/app/controllers/like_controller.rb
class LikeController < ApplicationController
  before_action :authenticate_user, only: [:destroy, :create]

  def show
    @like = Like.new
  end

  def create
    @like = Like.new(gossip_id: params[:id], user_id: current_user.id)

    if @like.save # essaie de sauvegarder en base @gossip
      # si ça marche, il redirige vers la page d'index du site
      puts "Tu as réussi"
      redirect_to gossips_path
    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      puts "ca ne fontionne pas"
      redirect_to gossips_path
    end
  end

  def destroy
    @like = Like.find(params[:id])
    like_user = @like.user

    if current_user == like_user
      @like.destroy
      redirect_to gossips_path
    else
      puts "pas possible"
      redirect_to gossips_path
    end
  end
end

the-gossip-project-rails-master 2/app/helpers/application_helper.rb
module ApplicationHelper
end

the-gossip-project-rails-master 2/app/helpers/city_helper.rb
module CityHelper
end

the-gossip-project-rails-master 2/app/helpers/comment_helper.rb
module CommentHelper
end

the-gossip-project-rails-master 2/app/helpers/contact_helper.rb
module ContactHelper
end

the-gossip-project-rails-master 2/app/helpers/gossips_helper.rb
module GossipsHelper
end

the-gossip-project-rails-master 2/app/helpers/like_helper.rb
module LikeHelper
end

the-gossip-project-rails-master 2/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
   User.find_by(id: session[:user_id])
  end

  def log_in(user)
   session[:user_id] = user.id
  end
end

the-gossip-project-rails-master 2/app/helpers/team_helper.rb
module TeamHelper
end

the-gossip-project-rails-master 2/app/helpers/user_helper.rb
module UserHelper
end

the-gossip-project-rails-master 2/app/helpers/welcomes_helper.rb
module WelcomesHelper
end

the-gossip-project-rails-master 2/app/views/gossips/edit.html.erb
<div class="card create-potin">
  <div class="card-header">
    <h2>Edition du potin</h2>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <%= form_for(@gossip) do |f| %>
          <%= f.text_field :title, class: 'form-control' %>
          <%= f.text_area :content, class: 'form-control' %>
          <%= f.submit %>
      <% end %>
    </blockquote>
  </div>
</div>

the-gossip-project-rails-master 2/app/views/gossips/index.html.erb
<p><%= link_to "Par ici si tu veux créer un nouveau potin", new_gossip_path, class: 'navbar-brand' %></p>

<h3>Hello visiteur ! Voici tous les potins de THP :</h3>

<div class="row">
  <% @gossips.each do |gossip| %>
    <div class="col-sm-4" style="padding: 30px">
      <div class="card">
        <div class="card-header">
          <h4><%= gossip.title %></h4>
        </div>
        <div class="card-body">
          <h5 class="card-title">A été écrit par <%= gossip.user.first_name %></h5>
          <%= link_to "En savoir plus...", gossip_path(gossip.id), class:"btn btn-primary" %>
          <% if gossip.likes.where(user_id: current_user).count > 0 %>
            <%= link_to "Dislike", like_path(:id => gossip.likes.sample), class:"btn btn-danger", data: { method: "DELETE" } %>
          <% else %>
            <%= link_to "liker", like_index_path(:id => gossip.id), class:"btn btn-danger", data: { method: "post" } %>
          <% end %>
          <%= gossip.likes.count %>
          <% if current_user == gossip.user %>
            <%= link_to "Editer", edit_gossip_path(gossip.id), class:"btn btn-default" %>
            <%= link_to "Supprimer", gossip_path(gossip.id), class:"btn btn-danger", data: {:confirm => "Etes vous sûr de supprimer ?", :method => "DELETE"} %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

the-gossip-project-rails-master 2/app/views/gossips/new.html.erb
<% if @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="card create-potin">
  <div class="card-header">
    <h2>Création d'un potin</h2>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <%= form_tag url_for(action: 'create'), method: "post" do %>

        <%= label_tag 'Titre de ton potin' %>
        <%= text_field_tag 'title' %>
        <br /> <br />

        <%= label_tag 'Description de ton potin' %>
        <%= text_area_tag 'content' %>
        <br /> <br />

        <%= submit_tag "Soumet ton potin" %>

      <% end %>
    </blockquote>
  </div>
</div>

the-gossip-project-rails-master 2/app/views/gossips/page.html.erb
<div class="card card-gossip">
  <div class="card-header">
    <H2><%= @gossip.title %></h2>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @gossip.content %></p>
      <footer class="blockquote-footer">Cet article a été écrit par "<%= @gossip.user.first_name %>" : <%= link_to "plus d'infos sur l'auteur", user_path(:user => @gossip.user.id) %></footer>
    </blockquote>
  </div>
</div>

the-gossip-project-rails-master 2/app/views/gossips/show.html.erb
<div class="card card-gossip">
  <div class="card-header">
    <H2><%= @gossip.title %></h2>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @gossip.content %></p>
      <footer class="blockquote-footer">Cet article a été écrit par <b><%= @gossip.user.first_name %></b> de la ville de <b><%= link_to @gossip.user.city.name, city_path(@gossip.user.city_id) %></b> : <%= link_to "plus d'infos sur l'auteur", user_path(@gossip.user.id) %></footer>
      <% if @gossip.likes.where(user_id: current_user).count > 0 %>
        <%= link_to "Dislike", like_path(:id => @gossip.likes.sample), class:"btn btn-danger", data: { method: "DELETE" } %>
      <% else %>
        <%= link_to "liker", like_index_path(:id => @gossip.id), class:"btn btn-danger", data: { method: "post" } %>
      <% end %>
      <%= @gossip.likes.count %>
    </blockquote>
  </div>
</div>

<div class="card create-potin">
  <div class="card-header">
    <h2>Commenter le gossip</h2>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <%= form_tag url_for(controller: :comment, action: :create, id: @gossip.id), method: "post" do %>

        <%= label_tag 'Description de ton potin' %>
        <%= text_area_tag 'content' %>
        <br /> <br />

        <%= submit_tag "Commenter" %>

      <% end %>
    </blockquote>
    <% @gossip.comments.each do |comment| %>
      <h5>A été écrit par <%= comment.user.first_name %> :</h5>
      <p><%= comment.content %>
        <% if current_user == comment.user %>
          <%= link_to "Editer", edit_comment_path(comment.id) %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>